---
title: "GISphere微信推送文章可视化统计"
author: "GISphere"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: true
---

## 总推送文章概况

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(openxlsx)

typeu <- c('留学经验', '留学生活', '对话访谈', '海外资讯')

gisjyfx <- read.xlsx('分配.xlsx', sheet = 1, startRow = 2)
gisjyfx$type <- typeu[1]
gisother <- read.xlsx('分配.xlsx', sheet = 2, startRow = 2)
gisother$type <- typeu[2]
for (i in 3:4) {
  gisotheru <- read.xlsx('分配.xlsx', sheet = i, startRow = 2)
  gisotheru$type <- typeu[i]
  gisother <- rbind(gisother, gisotheru)
  
}

print(paste('目前已推送文章：', nrow(na.omit(gisjyfx[, 1:11])) + 
              nrow(na.omit(gisother)) + 1, sep = ''))
```

### 分类型统计

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)

dfsta <- data.frame(type = typeu, num = c(20, 3, 1, 2))

p <- plot_ly(dfsta, labels = ~type, values = ~num, type = 'pie')%>%
  layout(title = '不同类型推送文章数量',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
p

```


## 留学经验推送相关统计

地区

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(plotly)

gisjyfxdf <- na.omit(gisjyfx[, 1:11])

regiondf <- data.frame(table(gisjyfxdf$地区))
colnames(regiondf) <- c('countries', 'num')

p1 <- ggplot(regiondf) + 
  geom_bar(mapping = aes(x = countries, y = num, fill = countries), colour = NA, stat = 'identity') + 
  labs(x = '地区', y = '数量')
p1 <- ggplotly(p1)
  
p1  
```

年份

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)

gisjyfxdf <- na.omit(gisjyfx[, 1:11])

yeardf <- data.frame(table(gisjyfxdf$Year))
colnames(yeardf) <- c('year', 'num')

p2 <- ggplot(yeardf) + 
  geom_bar(mapping = aes(x = year, y = num, fill = year), colour = NA, stat = 'identity') + 
  labs(x = '年份', y = '数量')
p2 <- ggplotly(p2)
  
p2
```

MS/PhD

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)

gisjyfxdf <- na.omit(gisjyfx[, 1:11])

msphddf <- data.frame(table(gisjyfxdf$`MS/PHD`))
colnames(msphddf) <- c('degree', 'num')

p3 <- ggplot(msphddf) + 
  geom_bar(mapping = aes(x = degree, y = num, fill = degree), colour = NA, stat = 'identity') + 
  labs(x = '学位', y = '数量')
p3 <- ggplotly(p3)
  
p3
```


