---
title: "GISphere微信推送文章统计"
author: "GISphere"
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 8
    fig_height: 4
    df_print: kable
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# 总推送文章概况

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(openxlsx)

typeu <- c('留学经验', '留学生活', '对话访谈', '海外资讯')

gisjyfx <- read.xlsx('../分配.xlsx', sheet = 1, startRow = 2)
gisjyfx$type <- typeu[1]
gistlist <- list()
gistlist[[1]] <- gisjyfx
for (i in 2:4) {
  gisotheru <- read.xlsx('../分配.xlsx', sheet = i, startRow = 2)
  gisotheru$type <- typeu[i]
  gistlist[[i]] <- gisotheru
}

print(paste('目前已推送文章：', nrow(gisjyfx[which(gisjyfx$状态=='已发布'), ]) + 
              nrow(gistlist[[2]][which(gistlist[[2]]$状态=='已发布'), ]) + 
              nrow(gistlist[[3]][which(gistlist[[3]]$状态=='已发布'), ]) + 
              nrow(gistlist[[4]][which(gistlist[[4]]$状态=='已发布'), ]) + 1, sep = ''))

```

### 分类型统计

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)

dfsta <- data.frame(type = typeu, num = c(nrow(gisjyfx[which(gisjyfx$状态=='已发布'), ]), 
                                          nrow(gistlist[[2]][which(gistlist[[2]]$状态=='已发布'), ]), 
                                          nrow(gistlist[[3]][which(gistlist[[3]]$状态=='已发布'), ]), 
                                          nrow(gistlist[[4]][which(gistlist[[4]]$状态=='已发布'), ])))

p <- plot_ly(dfsta, labels = ~type, values = ~num, type = 'pie')%>%
  layout(title = '不同类型推送文章数量',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
p

```


# 留学经验推送相关统计

地区

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(plotly)

gisjyfxdf <- gisjyfx[which(gisjyfx$状态=='已发布'), c(1, 4:12, 14)]
colnames(gisjyfxdf) <- c('Date', 'ID', 'Region', 'School', 'MSPHD', 'Title', 'Year', 'Note', 'Author', 'Editor', 'Status')

regiondf <- data.frame(table(gisjyfxdf$Region))
colnames(regiondf) <- c('region', 'num')

p1 <- ggplot(regiondf) + 
  geom_bar(mapping = aes(x = region, y = num, fill = region), colour = NA, stat = 'identity') + 
  labs(x = '地区', y = '数量', fill = '地区')
p1 <- ggplotly(p1)
  
p1  
```

年份

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)

gisjyfxdf <- gisjyfx[which(gisjyfx$状态=='已发布'), c(1, 4:12, 14)]
colnames(gisjyfxdf) <- c('Date', 'ID', 'Region', 'School', 'MSPHD', 'Title', 'Year', 'Note', 'Author', 'Editor', 'Status')

yeardf <- data.frame(table(gisjyfxdf$Year))
colnames(yeardf) <- c('year', 'num')

p2 <- ggplot(yeardf) + 
  geom_bar(mapping = aes(x = year, y = num, fill = year), colour = NA, stat = 'identity') + 
  labs(x = '年份', y = '数量', fill = '年份')
p2 <- ggplotly(p2)
  
p2
```

MS/PhD

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)

gisjyfxdf <- gisjyfx[which(gisjyfx$状态=='已发布'), c(1, 4:12, 14)]
colnames(gisjyfxdf) <- c('Date', 'ID', 'Region', 'School', 'MSPHD', 'Title', 'Year', 'Note', 'Author', 'Editor', 'Status')

msphddf <- data.frame(table(gisjyfxdf$MSPHD))
colnames(msphddf) <- c('degree', 'num')

p3 <- ggplot(msphddf) + 
  geom_bar(mapping = aes(x = degree, y = num, fill = degree), colour = NA, stat = 'identity') + 
  labs(x = '学位', y = '数量', fill = '学位')
p3 <- ggplotly(p3)
  
p3
```